# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

model:
  _name: resi_dual
  dropout: 0.1
  activation_dropout: 0.1
  attention_dropout: 0.1
  encoder:
    embed_dim: 512
    ffn_embed_dim: 2048
    layers: 18
    attention_heads: 8
  decoder:
    embed_dim: 512
    ffn_embed_dim: 2048
    layers: 18
    attention_heads: 8
  enc_alpha: 1.0
  dec_alpha: 1.0
  share_decoder_input_output_embed: true
  share_all_embeddings: false
  enc_res_input_norm_scale: 0.05
  dec_res_input_norm_scale: 0.05
  base_layers: 0
  max_source_positions: 256
  max_target_positions: 256

dataset:
  max_tokens: 4096
  num_workers: 24
  valid_subset: 'valid'
  skip_invalid_size_inputs_valid_test: true

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  # weight_decay: 0.0001

optimization:
  max_update: 100000
  lr: [0.004]
  clip_norm: 1.0
  update_freq: [16]

lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 8000
  warmup_init_lr: 1e-7

criterion:
  _name: label_smoothed_cross_entropy
  label_smoothing: 0.1

task:
  _name: translation_multi_simple_epoch_hydra 
  data: '???'
  sampling_method: linear
  sampling_temperature: 5
  min_sampling_temperature: 1.0
  warmup_epoch: 5
  encoder_langtok: tgt
  langtoks:
    main: [tgt, null]
  langs: [af,am,ar,as,az,be,bg,bn,br,bs,ca,cs,cy,da,de,el,en,eo,es,et,eu,fa,fi,fr,fy,ga,gd,gl,gu,ha,he,hi,hr,hu,id,ig,is,it,ja,ka,kk,km,kn,ko,ku,ky,li,lt,lv,mg,mk,ml,mr,ms,mt,my,nb,ne,nl,nn,'no',oc,or,pa,pl,ps,pt,ro,ru,rw,se,sh,si,sk,sl,sq,sr,sv,ta,te,tg,th,tk,tr,tt,ug,uk,ur,uz,vi,wa,xh,yi,zh,zu]
  lang_pairs: [es-en,en-es,fr-en,en-fr,ro-en,en-ro,nl-en,en-nl,cs-en,en-cs,el-en,en-el,hu-en,en-hu,pl-en,en-pl,tr-en,en-tr,pt-en,en-pt,bg-en,en-bg,it-en,en-it,fi-en,en-fi,hr-en,en-hr,ar-en,en-ar,sr-en,en-sr,he-en,en-he,de-en,en-de,sl-en,en-sl,ru-en,en-ru,sv-en,en-sv,da-en,en-da,et-en,en-et,bs-en,en-bs,sk-en,en-sk,id-en,en-id,no-en,en-no,fa-en,en-fa,lt-en,en-lt,zh-en,en-zh,lv-en,en-lv,mk-en,en-mk,vi-en,en-vi,th-en,en-th,ja-en,en-ja,sq-en,en-sq,ms-en,en-ms,is-en,en-is,ko-en,en-ko,uk-en,en-uk,ca-en,en-ca,eu-en,en-eu,mt-en,en-mt,gl-en,en-gl,ml-en,en-ml,bn-en,en-bn,pa-en,en-pa,hi-en,en-hi,ta-en,en-ta,si-en,en-si,nb-en,en-nb,nn-en,en-nn,te-en,en-te,gu-en,en-gu,mr-en,en-mr,ne-en,en-ne,kn-en,en-kn,or-en,en-or,as-en,en-as,ka-en,en-ka,be-en,en-be,eo-en,en-eo,cy-en,en-cy,ga-en,en-ga,ug-en,en-ug,az-en,en-az,xh-en,en-xh,af-en,en-af,oc-en,en-oc,br-en,en-br,rw-en,en-rw,km-en,en-km,ku-en,en-ku,wa-en,en-wa,mg-en,en-mg,kk-en,en-kk,tg-en,en-tg,am-en,en-am,ps-en,en-ps,my-en,en-my,uz-en,en-uz,ur-en,en-ur,ky-en,en-ky,gd-en,en-gd,sh-en,en-sh,li-en,en-li,zu-en,en-zu,fy-en,en-fy,tk-en,en-tk,yi-en,en-yi,tt-en,en-tt,se-en,en-se,ha-en,en-ha,ig-en,en-ig]
  enable_lang_ids: true
  same_lang_per_batch: true
  enable_reservsed_directions_shared_datasets: true
  truncate_source: true


checkpoint:
  no_epoch_checkpoints: true

common:
  azureml_logging: true
  log_format: simple
  # amp: true
  fp16: true
  memory_efficient_fp16: true
  fp16_init_scale: 8
  seed: 1379

distributed_training:
  find_unused_parameters: true
  ddp_backend: fully_sharded

hydra:
  run:
    dir: ???